docs_dir: docs/

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nathonfowlie/
      name: LinkedIn

extra_css:
  - css/extra.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - ...

plugins:
  - awesome-pages:
      collapse_single_pages: true
  - search:
      prebuild_index: true
  - macros
  - mermaid2:
      arguments:
        securityLevel: 'loose'

repo_name: 'nathonfowlie/education.aws.developer_associate'
repo_url: 'https://github.com/nathonfowlie/education.aws.developer_associate'

site_author: Nathon Fowlie
site_description: 'Study notes for the AWS Developer Associate 2021 Exam.'
site_name: AWS Developer Associate 2021

theme:
  features:
    - navigation.instant
    - navigation.top
    - search.suggest
    - toc.integrate
  icon:
    repo: fontawesome/brands/github-square
  name: 'material'
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
