docs_dir: docs/

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nathonfowlie/
      name: LinkedIn

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - 'Fundamentals':
      - 'AWS Certificate Manager': fundamentals/acm.md
      - 'Auto-scaling Groups': fundamentals/asg.md
      - 'Aurora': fundamentals/aurora.md
      - 'Databases': fundamentals/databases.md
      - 'EBS': fundamentals/ebs.md
      - 'EC2': fundamentals/ec2.md
      - 'ElastiCache': fundamentals/elasticache.md
      - 'Elastic File System': fundamentals/efs.md
      - 'Elastic Load Balancers': fundamentals/elb.md
      - 'Identity & Access Management': fundamentals/iam.md
      - 'Relational Database Service': fundamentals/rds.md
      - 'Route53': fundamentals/route53.md
      - 'S3': fundamentals/s3.md
      - 'SES': fundamentals/ses.md
      - 'VPC': fundamentals/vpc.md
  - 'CI/CD':
      - 'CodeCommit': cicd/codecommit.md
      - 'CodePipeline': cicd/codepipeline.md
      - 'CodeBuild': cicd/codebuild.md
      - 'CodeDeploy': cicd/codedeploy.md
      - 'CodeStar': cicd/codestar.md
  - 'Developing on AWS':
      - 'Athena': developing/athena.md
      - 'Command Line Interface': developing/cli.md
      - 'AWS SDK': developing/sdk.md
      - 'CloudFormation': developing/cloudformation.md
      - 'CloudFront': developing/cloudfront.md
      - 'Elastic Beanstalk': developing/elasticbeanstalk.md
      - 'ECR': developing/ecr.md
      - 'ECS': developing/ecs.md
      - 'Fargate': developing/fargate.md
      - 'STS': developing/sts.md
      - 'Directory Services': developing/ds.md
      - 'Step Functions': developing/stepfunctions.md
      - 'AppSync': developing/appsync.md
      - 'CloudWatch': developing/cloudwatch.md
      - 'X-Ray': developing/xray.md
      - 'CloudTrail': developing/cloudtrail.md
  - 'Messaging':
      - 'SQS': messaging/sqs.md
      - 'SNS': messaging/sns.md
      - 'Kinesis': messaging/kinesis.md
  - 'Identity Management':
      - 'Cognito': identitymanagement/cognito.md

plugins:
  - search:
      prebuild_index: true
  - macros
  - mermaid2:
      arguments:
        securityLevel: 'loose'

repo_name: 'nathonfowlie/education.aws.developer_associate'
repo_url: 'https://github.com/nathonfowlie/education.aws.developer_associate'

site_author: Nathon Fowlie
site_description: 'Study notes for the AWS Developer Associate 2021 Exam.'
site_name: AWS Developer Associate 2021

theme:
  features:
    - navigation.expand
    - navigation.instant
      #- navigation.sections
    - navigation.tabs
    - navigation.top
    - search.suggest
    - toc.integrate
  icon:
    repo: fontawesome/brands/github-square
  name: 'material'
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
